import type { Metadata } from "next"

import "./globals.css"

import { Poppins } from "next/font/google"

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body className={`${poppins.className} antialiased`}>
                    {children}
                </body>
            </html>
        </>
    )
}
